import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { motion } from "framer-motion";
import MetricCard from "../components/MetricCard";
import ScoreGauge from "../components/ScoreGauge";
import ComplexityChart from "../components/ComplexityChart";
import MaintainabilityChart from "../components/MaintainabilityChart";
import FunctionTable from "../components/FunctionTable";
import type { AnalysisResult } from "../types";

type Tab = "overview" | "functions" | "duplicates";

const TABS: { id: Tab; label: (data: AnalysisResult) => string }[] = [
  { id: "overview",   label: ()   => "Overview" },
  { id: "functions",  label: (d)  => `Functions (${d.functions.length})` },
  { id: "duplicates", label: (d)  => `Duplicates (${d.duplicates.length})` },
];

function downloadJSON(data: AnalysisResult) {
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = "code-quality-report.json";
  a.click();
  URL.revokeObjectURL(a.href);
}

function downloadHTML(data: AnalysisResult) {
  const s = data.summary;
  const rows = data.functions
    .map(
      (f) =>
        `<tr><td>${f.file}</td><td>${f.function}</td><td>${f.complexity}</td>` +
        `<td>${f.maintainability}</td><td>${f.line_count || "—"}</td>` +
        `<td>${f.is_duplicate ? "Yes" : "No"}</td></tr>`
    )
    .join("");
  const html = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8">
<title>Code Quality Report</title>
<style>
  body{font-family:Inter,system-ui,sans-serif;background:#0D1117;color:#C9D1D9;padding:2rem;margin:0}
  h1{color:#58A6FF;margin-bottom:.25rem}
  h2{color:#E6EDF3;border-bottom:1px solid #30363D;padding-bottom:.5rem;margin-top:2rem}
  table{border-collapse:collapse;width:100%;margin-top:1rem}
  th,td{border:1px solid #30363D;padding:.5rem .75rem;text-align:left;font-size:.875rem}
  th{background:#161B22;color:#8B949E;text-transform:uppercase;font-size:.75rem;letter-spacing:.05em}
  .score{font-size:2.5rem;font-weight:700;color:#E6EDF3}
  ul{list-style:none;padding:0;display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:1rem}
  li{background:#161B22;border:1px solid #30363D;border-radius:.5rem;padding:1rem}
  li b{display:block;font-size:1.5rem;color:#E6EDF3;margin-top:.25rem}
</style></head><body>
<h1>Code Quality Report</h1>
<p style="color:#8B949E">Generated by CodeQuality Analyzer</p>
<h2>Summary</h2>
<div class="score">${s.overall_score}<span style="font-size:1rem;color:#8B949E">/100</span></div>
<ul style="margin-top:1.5rem">
  <li>Files analyzed<b>${s.total_files}</b></li>
  <li>Functions found<b>${s.total_functions}</b></li>
  <li>Avg Complexity<b>${s.avg_complexity}</b></li>
  <li>Avg Maintainability<b>${s.avg_maintainability}</b></li>
  <li>Long Functions<b>${s.long_functions_count}</b></li>
  <li>Duplicates<b>${s.duplicates_count}</b></li>
</ul>
<h2>Function Details</h2>
<table>
  <tr><th>File</th><th>Function</th><th>Complexity</th><th>Maintainability</th><th>Lines</th><th>Duplicate</th></tr>
  ${rows}
</table>
</body></html>`;
  const blob = new Blob([html], { type: "text/html" });
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = "code-quality-report.html";
  a.click();
  URL.revokeObjectURL(a.href);
}

export default function ResultsPage() {
  const navigate = useNavigate();
  const [data, setData] = useState<AnalysisResult | null>(null);
  const [tab, setTab] = useState<Tab>("overview");

  useEffect(() => {
    const raw = sessionStorage.getItem("analysisResult");
    if (!raw) { navigate("/analyze"); return; }
    try { setData(JSON.parse(raw)); }
    catch { navigate("/analyze"); }
  }, [navigate]);

  if (!data) return null;

  const { summary, functions, duplicates } = data;

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 py-10">
      {/* ── Header ───────────────────────────────────────────── */}
      <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4 mb-8">
        <motion.div initial={{ opacity: 0, y: -8 }} animate={{ opacity: 1, y: 0 }}>
          <h1 className="text-2xl font-bold" style={{ color: "var(--text-primary)" }}>
            Analysis Results
          </h1>
          <p className="text-sm mt-1" style={{ color: "var(--text-muted)" }}>
            {summary.total_files} file{summary.total_files !== 1 ? "s" : ""} ·{" "}
            {summary.total_functions} function{summary.total_functions !== 1 ? "s" : ""} ·{" "}
            Python AST
          </p>
        </motion.div>

        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.1 }}
          className="flex gap-2 flex-shrink-0"
        >
          <button
            onClick={() => downloadJSON(data)}
            className="flex items-center gap-1.5 px-3 py-2 rounded-lg text-xs font-medium border transition-all hover:opacity-80"
            style={{ borderColor: "var(--border)", color: "var(--text-muted)", background: "var(--surface)" }}
          >
            <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4M7 10l5 5 5-5M12 15V3"/>
            </svg>
            JSON
          </button>
          <button
            onClick={() => downloadHTML(data)}
            className="flex items-center gap-1.5 px-3 py-2 rounded-lg text-xs font-medium border transition-all hover:opacity-80"
            style={{ borderColor: "var(--border)", color: "var(--text-muted)", background: "var(--surface)" }}
          >
            <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z"/>
              <polyline points="14 2 14 8 20 8"/>
            </svg>
            HTML
          </button>
          <button
            onClick={() => navigate("/analyze")}
            className="flex items-center gap-1.5 px-3 py-2 rounded-lg text-xs font-medium border transition-all hover:opacity-80"
            style={{ borderColor: "var(--border)", color: "var(--text-muted)", background: "var(--surface)" }}
          >
            ← New
          </button>
        </motion.div>
      </div>

      {/* ── Tabs ─────────────────────────────────────────────── */}
      <div
        className="flex gap-1 mb-8 p-1 rounded-lg w-fit"
        style={{ background: "var(--surface)", border: "1px solid var(--border)" }}
      >
        {TABS.map((t) => (
          <button
            key={t.id}
            onClick={() => setTab(t.id)}
            className="px-4 py-1.5 rounded-md text-sm font-medium transition-all"
            style={{
              background: tab === t.id ? "var(--primary-muted)" : "transparent",
              border: `1px solid ${tab === t.id ? "var(--primary-dim)" : "transparent"}`,
              color: tab === t.id ? "var(--primary)" : "var(--text-muted)",
            }}
          >
            {t.label(data)}
          </button>
        ))}
      </div>

      {/* ── Overview ─────────────────────────────────────────── */}
      {tab === "overview" && (
        <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: 0.25 }}>
          {/* Score + metric cards */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
            <ScoreGauge score={summary.overall_score} />

            <MetricCard
              index={1}
              title="Avg Complexity"
              value={summary.avg_complexity}
              subtitle={
                summary.avg_complexity <= 3 ? "Low — healthy"
                : summary.avg_complexity <= 6 ? "Medium — watch it"
                : "High — refactor soon"
              }
              color={
                summary.avg_complexity <= 3 ? "var(--success)"
                : summary.avg_complexity <= 6 ? "var(--warning)"
                : "var(--danger)"
              }
              icon={
                <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <polyline points="22 12 18 12 15 21 9 3 6 12 2 12"/>
                </svg>
              }
            />

            <MetricCard
              index={2}
              title="Avg Maintainability"
              value={summary.avg_maintainability}
              subtitle={
                summary.avg_maintainability >= 70 ? "Excellent"
                : summary.avg_maintainability >= 40 ? "Moderate"
                : "Needs attention"
              }
              color={
                summary.avg_maintainability >= 70 ? "var(--success)"
                : summary.avg_maintainability >= 40 ? "var(--warning)"
                : "var(--danger)"
              }
              icon={
                <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z"/>
                </svg>
              }
            />

            {/* Two stacked mini cards */}
            <div className="flex flex-col gap-4">
              <MetricCard
                index={3}
                title="Long Functions"
                value={summary.long_functions_count}
                subtitle={summary.long_functions_count === 0 ? "None detected" : "Exceeds 50 lines"}
                color="var(--warning)"
                icon={
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <line x1="8" y1="6" x2="21" y2="6"/><line x1="8" y1="12" x2="21" y2="12"/><line x1="8" y1="18" x2="14" y2="18"/>
                    <line x1="3" y1="6" x2="3.01" y2="6"/><line x1="3" y1="12" x2="3.01" y2="12"/><line x1="3" y1="18" x2="3.01" y2="18"/>
                  </svg>
                }
              />
              <MetricCard
                index={4}
                title="Duplicates"
                value={summary.duplicates_count}
                subtitle={summary.duplicates_count === 0 ? "None detected" : "Functions duplicated"}
                color="var(--danger)"
                icon={
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <rect x="9" y="9" width="13" height="13" rx="2"/>
                    <path d="M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1"/>
                  </svg>
                }
              />
            </div>
          </div>

          {/* Charts */}
          <div className="grid lg:grid-cols-2 gap-5 mb-6">
            <motion.div
              initial={{ opacity: 0, y: 16 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.25 }}
              className="rounded-xl border p-5"
              style={{ background: "var(--surface)", borderColor: "var(--border)", boxShadow: "var(--shadow-sm)" }}
            >
              <h3 className="text-sm font-semibold mb-1" style={{ color: "var(--text-primary)" }}>
                Complexity by Function
              </h3>
              <p className="text-xs mb-5" style={{ color: "var(--text-muted)" }}>
                Top 15 functions · Green ≤3 · Yellow ≤6 · Red {">"} 6
              </p>
              <ComplexityChart functions={functions} />
            </motion.div>

            <motion.div
              initial={{ opacity: 0, y: 16 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.32 }}
              className="rounded-xl border p-5"
              style={{ background: "var(--surface)", borderColor: "var(--border)", boxShadow: "var(--shadow-sm)" }}
            >
              <h3 className="text-sm font-semibold mb-1" style={{ color: "var(--text-primary)" }}>
                Maintainability Distribution
              </h3>
              <p className="text-xs mb-5" style={{ color: "var(--text-muted)" }}>
                Functions grouped by maintainability score
              </p>
              <MaintainabilityChart functions={functions} />
            </motion.div>
          </div>

          {/* Files summary */}
          <motion.div
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.38 }}
            className="rounded-xl border p-5"
            style={{ background: "var(--surface)", borderColor: "var(--border)", boxShadow: "var(--shadow-sm)" }}
          >
            <h3 className="text-sm font-semibold mb-4" style={{ color: "var(--text-primary)" }}>
              Project Overview
            </h3>
            <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-4">
              {[
                { label: "Files",           value: summary.total_files },
                { label: "Functions",       value: summary.total_functions },
                { label: "Avg Complexity",  value: summary.avg_complexity },
                { label: "Avg Maintain.",   value: summary.avg_maintainability },
                { label: "Long Functions",  value: summary.long_functions_count },
                { label: "Duplicates",      value: summary.duplicates_count },
              ].map((item) => (
                <div key={item.label} className="text-center">
                  <p className="text-2xl font-bold tabular-nums" style={{ color: "var(--text-primary)" }}>
                    {item.value}
                  </p>
                  <p className="text-xs mt-1" style={{ color: "var(--text-muted)" }}>{item.label}</p>
                </div>
              ))}
            </div>
          </motion.div>
        </motion.div>
      )}

      {/* ── Functions tab ─────────────────────────────────────── */}
      {tab === "functions" && (
        <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: 0.25 }}>
          <FunctionTable functions={functions} />
        </motion.div>
      )}

      {/* ── Duplicates tab ────────────────────────────────────── */}
      {tab === "duplicates" && (
        <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: 0.25 }}>
          {duplicates.length === 0 ? (
            <div
              className="rounded-xl border p-16 text-center"
              style={{ background: "var(--surface)", borderColor: "var(--border)" }}
            >
              <div
                className="w-12 h-12 rounded-full flex items-center justify-center mx-auto mb-4"
                style={{ background: "var(--success-muted)", color: "var(--success)" }}
              >
                <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <polyline points="20 6 9 17 4 12"/>
                </svg>
              </div>
              <p className="font-semibold mb-1" style={{ color: "var(--text-primary)" }}>No duplicates detected</p>
              <p className="text-sm" style={{ color: "var(--text-muted)" }}>
                All functions have unique implementations.
              </p>
            </div>
          ) : (
            <div className="space-y-3">
              {duplicates.map((d, i) => (
                <motion.div
                  key={i}
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: i * 0.05 }}
                  className="rounded-xl border p-5"
                  style={{
                    background: "var(--surface)",
                    borderColor: "color-mix(in srgb, var(--danger) 30%, var(--border))",
                  }}
                >
                  <div className="flex items-start gap-3">
                    <div
                      className="w-8 h-8 rounded-lg flex items-center justify-center flex-shrink-0 mt-0.5"
                      style={{ background: "var(--danger-muted)", color: "var(--danger)" }}
                    >
                      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                        <rect x="9" y="9" width="13" height="13" rx="2"/>
                        <path d="M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1"/>
                      </svg>
                    </div>
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-medium mb-3" style={{ color: "var(--text-primary)" }}>
                        Duplicate detected
                      </p>
                      <div className="grid sm:grid-cols-2 gap-3">
                        <div
                          className="rounded-lg p-3"
                          style={{ background: "var(--bg)", border: "1px solid var(--border)" }}
                        >
                          <p className="text-xs mb-1.5 font-semibold uppercase tracking-widest" style={{ color: "var(--text-muted)" }}>
                            Original
                          </p>
                          <p className="text-sm font-mono font-medium" style={{ color: "var(--primary)" }}>
                            {d.original_function}
                          </p>
                          <p className="text-xs mt-0.5" style={{ color: "var(--text-muted)" }}>
                            {d.original_file}
                          </p>
                        </div>
                        <div
                          className="rounded-lg p-3"
                          style={{
                            background: "var(--bg)",
                            border: "1px solid color-mix(in srgb, var(--danger) 30%, var(--border))",
                          }}
                        >
                          <p className="text-xs mb-1.5 font-semibold uppercase tracking-widest" style={{ color: "var(--text-muted)" }}>
                            Duplicate
                          </p>
                          <p className="text-sm font-mono font-medium" style={{ color: "var(--danger)" }}>
                            {d.duplicate_function}
                          </p>
                          <p className="text-xs mt-0.5" style={{ color: "var(--text-muted)" }}>
                            {d.duplicate_file}
                          </p>
                        </div>
                      </div>
                      <p className="text-xs mt-3" style={{ color: "var(--text-muted)" }}>
                        💡 Extract to a shared utility function to eliminate duplication and reduce maintenance burden.
                      </p>
                    </div>
                  </div>
                </motion.div>
              ))}
            </div>
          )}
        </motion.div>
      )}
    </div>
  );
}
